version: '3.8'
services:
  postgresql:
      container_name: postgresql_kodingkorp
      restart: unless-stopped
      environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          PGDATA : /var/lib/postgresql/data/pgdata
      image: postgres:latest
      ports:
          - 5432:5432
      volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
volumes:
  postgres_data: